name: config_gen
description: A starting point for Dart libraries or applications.
version: 0.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

dependencies:
  build: ^3.0.0
  source_gen: ^3.0.0
  meta: ^1.8.0
  analyzer: ^7.7.1
  config:
    # path: ../config.dart
    version: ^0.0.5
    git:
      url: https://github.com/ross96D/config.dart
      tag_pattern: "{{version}}"

dev_dependencies:
  build_runner: ^2.6.0
  lints: ^5.0.0
