name: config_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  build: ^3.0.0
  source_gen: ^3.0.0
  meta: ^1.8.0
  analyzer: ^7.7.1
  config:
    path: ../config.dart

dev_dependencies:
  build_runner: ^2.6.0
  lints: ^5.0.0
